# Generated by Django 5.1.15 on 2026-05-23 08:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sport_category', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('tennis', 'Tennis'), ('swimming', 'Swimming'), ('athletics', 'Athletics'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('boxing', 'Boxing'), ('cycling', 'Cycling'), ('motorsport', 'Motorsport'), ('other', 'Other')], default='other', max_length=30)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
