# Generated by Django 5.1.15 on 2026-05-23 08:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('favorite_sport', models.CharField(blank=True, choices=[('football', 'Football'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('baseball', 'Baseball'), ('tennis', 'Tennis'), ('swimming', 'Swimming'), ('athletics', 'Athletics'), ('volleyball', 'Volleyball'), ('hockey', 'Hockey'), ('other', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
