# Generated by Django 5.1.15 on 2026-05-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='sportsnap/photos/'),
        ),
    ]
