# Generated by Django 5.1.15 on 2026-05-23 08:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sport_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
